### ISSUE TITLE
Documentation Getting-started-setup-the-game-project has a compiler error

### ISSUE THREAD

**Issue by patricksan** [gurkenlabs/litiengine-docs#3]
In the current page: https://litiengine.com/getting-started-setup-the-game-project/

It says:
```
  public static void main(String[] args) {
    Game.init();
    Game.start(args);
  }
```

But it should be:

```
  public static void main(String[] args) {
    Game.init(args);
    Game.start();
  }
```

**Comment by steffen-wilke** [comment]
Thank you for reporting this. With the relaunch of our Docs pages with the new upcoming website, this blog post will be archived and its content will be migrated to MarkDown format (see #2). I've just checked this and the described problem is not present in the migrated content.

Nevertheless, I've also fixed the issue on the current blog post since it will still be online for some time (until we release our new website).
